### ISSUE TITLE
Inverse Kinematics Issue

### ISSUE THREAD

**Issue by fionalluo** [perezjln/gym-lowcostrobot#35]
Hi, I noticed when testing the inverse_kinematics method in the LiftCubeCamera environment in simulation to set the robot end effector to a specified position, inverse_kinematics doesn't seem to output the correct joint actions. 

I tested this by calling inverse_kinematics with the link_6 geom_xpos at a resting arm position. However, the robot tends to stretch its end effector very far out instead.

I was wondering what could cause this issue? Thank you for the help!

**Comment by perezjln** [comment]
Thanks @fionalluo for your message, would you have by any chance a code that illustrates the situation you are describing please.

@michel-aractingi - Maybe one should not put the inverse kinematic code in every environment despiste the one file standard thing. what do you think ?

**Comment by fionalluo** [comment]
Thanks for the reply! I was able to mostly fix the inverse kinematics method by switching to using end_effector instead of link_6, and switching all the "body" to "site" since the end_effector is a site while link_6 is a body. 

This is able to perform IK for the end effector, only downside is that this only guarantees the position and not rotation of the end_effector. So most of the time the end effector is diagonal which is not good for tasks like lift cube. Perhaps that's why link_6 was used in the first place?

Would definitely be helpful to have the IK code in one standard file. Thanks again!

**Comment by AbdElRahmanFarhan** [comment]
> Thanks for the reply! I was able to mostly fix the inverse kinematics method by switching to using end_effector instead of link_6, and switching all the "body" to "site" since the end_effector is a site while link_6 is a body.
> 
> This is able to perform IK for the end effector, only downside is that this only guarantees the position and not rotation of the end_effector. So most of the time the end effector is diagonal which is not good for tasks like lift cube. Perhaps that's why link_6 was used in the first place?
> 
> Would definitely be helpful to have the IK code in one standard file. Thanks again!

Hi @fionalluo 

I am facing the same problem. Could you please elaborate more on how you solved it
