### ISSUE TITLE
Cannot setup with Windows11, potentially mujoco issue

### ISSUE THREAD

**Issue by dibbla** [perezjln/gym-lowcostrobot#36]
Hi @perezjln 

Thanks for the great work! 

Currently I am using the standard installation script provided in README but some how cannot run the sample code:
```python
import gymnasium as gym
import gym_lowcostrobot # Import the low-cost robot environments

# Create the environment
env = gym.make("PickPlaceCube-v0", render_mode="human")

# Reset the environment
observation, info = env.reset()

for _ in range(1000):
    # Sample random action
    action = env.action_space.sample()

    # Step the environment
    observation, reward, terminted, truncated, info = env.step(action)

    # Reset the environment if it's done
    if terminted or truncated:
        observation, info = env.reset()

# Close the environment
env.close()
```

Here is the error message:
```
Traceback (most recent call last):
  File "D:\lerobot_on_win\test_script\test_env.py", line 5, in <module>
    env = gym.make("PickPlaceCube-v0", render_mode="human")
  File "D:\miniconda3\envs\lerobot\lib\site-packages\gymnasium\envs\registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "D:\miniconda3\envs\lerobot\lib\site-packages\gym_lowcostrobot\envs\pick_place_cube_env.py", line 80, in __init__
    self.model = mujoco.MjModel.from_xml_path(os.path.join(ASSETS_PATH, "pick_place_cube.xml"), {})
ValueError: XML Error: Schema violation: unrecognized attribute: 'convexhull'

Element 'compiler', line 2
```

Any suggestion?

**Comment by dibbla** [comment]
Update: seems like only the pick&place environment has such issue.

**Comment by alexcbb** [comment]
Hi, I had the same issue and it seems to be a mujoco version issue. On my side I just removed the "convexhull" param in the mujoco environment definition assets/low_cost_robot_6dof/pick_place_cube.xml , on line 2. It seems to work now (I don't know if this is a proper fix tho)

**Comment by s1lent4gnt** [comment]
The latest MuJoCo version (3.2.5) has removed the convexhull compiler attribute. You can find more details in the [changelog](https://mujoco.readthedocs.io/en/latest/changelog.html#version-3-2-5-nov-4-2024).

**Comment by dibbla** [comment]
Thanks folks @s1lent4gnt @alexcbb :>

The issue is fixed and I am closing the issue.
